#%RAML 1.0
title: Weekly Menu API
version: v1
baseUri: http://api.samplehost.com

#Security scheme
securitySchemes:
  basic: !include securitySchemes/basic.raml

#Resource Types definition
resourceTypes:
  collection: !include resourceTypes/collection.raml
  element: !include resourceTypes/element.raml

#Traits definition
traits:
  pageable: !include traits/pageable.raml

#Types definition
types:
  Recipe: !include dataTypes/recipe.raml
  Ingredient: !include dataTypes/ingredient.raml
  Menu: !include dataTypes/menu.raml
  DayOfWeek: !include dataTypes/dayOfWeek.raml
  ShoppingList: !include dataTypes/shoppingList.raml

/ingredients:
  type: collection
  is:  [pageable]
  /{ingredientId}:
    type: element

/recipes:
  type: collection
  is:  [pageable]
  /{recipeId}:
    type: element

/menus:
  type: collection
  is:  [pageable]
  /{menuId}:
    type: element
  /{date}:
    uriParameters:
      date:
        type: date-only
    type: collection

/shopping:
  /list:
    get:
      responses:
        200:
          body:
            application/json:
              type: ShoppingList
  /day:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                dayOfWeek: DayOfWeek
    put:
      body:
        application/json:
          type: object
          properties:
            dayOfWeek: DayOfWeek
