#%RAML 1.0
title: Weekly Menu API
version: v1
baseUri: http://api.samplehost.com

#Security scheme
securitySchemes:
  basic: !include securitySchemes/basic.raml

#Resource Types definition
resourceTypes:
  collection:
    usage: This resourceType should be used for any collection of items
    description: The collection of <<resourcePathName>>
    get:
      description: Get all <<resourcePathName>>, optionally filtered
      responses:
        200:
          body:
            application/json:
              type: array
              items: <<resourcePathName | !uppercamelcase>>
    post:
      description: Create a new <<resourcePathName | !singularize>>
      responses:
        201:
          body:
            application/json:
              type: <<resourcePathName | !uppercamelcase | !singularize>>

  element:
    usage: This resourceType should be used for any item of a collection of items
    description: An element of collection <<resourcePathName>>
    get:
      description: Get one <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName | !uppercamelcase | !singularize>>
    patch:
      description: Create a new <<resourcePathName | !singularize>>
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName | !uppercamelcase | !singularize>>
    delete:
      description: Delete one <<resourcePathName | !singularize>>
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName | !uppercamelcase | !singularize>>


#Traits definition
traits:
  pageable:
    usage: Apply this trait to a GET method that supports pagination.
    queryParameters:
      offset?:
        type: integer
        default: 10
        minimum: 0
        description: The `offset` parameter specifies the first entry to return from a collection.
      limit?:
        type: integer
        default: 50
        minimum: 1
        description: The `limit` parameter restricts the number of entries returned.
      page?:
        type: integer
        default: 1
        minimum: 1
    description: The `page` parameter specifies the page of results to return.


#Types definition
types:
  User:
    type: object
    properties:
      username: string
      name: string
      email: string
      shoppingDay:
        type: array
        items: DayOfWeek
        minItems: 1
        maxItems: 7

  Ingredient:
    type: object
    properties:
      name: string
      description: string
      note: string
      freezed: boolean
      availabilityMonths:
        type: array
        items: integer
      tags: 
        type: array
        items: string

  Recipe:
    type: object
    properties:
      name: string
      description: string
      note: string
      availabilityMonths:
        type: array
        items: integer
      ingredients:
        type: array
        items: Ingredient
      servs:
        type: integer
        description: how many people, this recipe, servs
      estimatedCookingTime: integer
      estimatedPreparationTime: integer

  Meal:
    type: string
    enum: ["breakfast", "launch", "dinner"]

  Menu:
    type: object
    properties:
      date: date-only
      meal: Meal
      recipes:
        type: array
        items: Recipe

  DayOfWeek:
    type: integer
    minimum: 1
    maximum: 7

  ShoppingList:
    type: object
    properties:
      ObjectId: string
      items:
        type: array
        items:
          type: Ingredient
          properties:
            checked: boolean
            shoppingNote: string

/auth:
  /register:
    description: Register new user
    post:
  /token:
    description: Retrieve a token given user credentials
    post:

/users:
  /me:
    securedBy: basic
    description: Retrieve informaion of the current user
    get:

/ingredients:
  type: collection
  is:  [pageable]
  /{ingredientId}:
    type: element

/recipes:
  type: collection
  is:  [pageable]
  /{recipeId}:
    type: element

/menus:
  type: collection
  is:  [pageable]
  /{menuId}:
    type: element
  /{date}:
    uriParameters:
      date:
        type: string
        description: date in format YYYY-MM-DD
    type: collection
  /generate:
    description: Generate new menu for the next week
    get:
      responses:
        201:
         body:
           application/json:
             type: Menu[]

/shopping:
  /list:
    description: Retrieve shopping list
    get:
      responses:
        200:
          body:
            application/json:
              type: ShoppingList
    /{itemId}:
      type: element
  /day:
    description: Get or set the designed day(s) of the week that indicates when the user is used to go to shopping
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                dayOfWeek: DayOfWeek[]
    put:
      body:
        application/json:
          type: object
          properties:
            dayOfWeek: DayOfWeek
