#%RAML 1.0 ResourceType

usage: This resourceType should be used for any collection of items
description: The collection of <<resourcePathName>>
get:
  description: Get all <<resourcePathName>>, optionally filtered
  responses:
    200:
      body:
        application/json:
          type: array
          items: <<resourcePathName | !uppercamelcase>>
post:
  description: Create a new <<resourcePathName | !singularize>>
  responses:
    201:
      body:
        application/json:
          type: <<resourcePathName | !uppercamelcase | !singularize>>
